import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  blogSidebar: [
    {
      type: 'category',
      label: 'علوم الحاسب الآلي',
      items: [
        {
          type: 'link',
          label: 'تجربة عبدالمجيد بكر - خريجة علوم الحاسب الآلي',
          href: 'https://example.com/blog/abdulmajeed-bakr', 
        },
        {
          type: 'link',
          label: 'تجربة حميدة خان - خريجة علوم الحاسب الآلي',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/hamida-khan',
        },
        {
          type: 'link',
          label: 'تجربة رهف مراد - خريجة علوم الحاسب الآلي',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/rahaf-murad',
        },
      ],
    },
    {
      type: 'category',
      label: 'هندسة البرمجيات',
      items: [
        {
          type: 'link',
          label: 'تجربة لينا نجدي - هندسة البرمجيات',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/Lina',
        },
        {
          type: 'link',
          label: 'تجربة شادي رزق - هندسة البرمجيات',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/Shadi',
        },
        {
          type: 'link',
          label: 'تجربة الكاتو - هندسة البرمجيات',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/elcato',
        },
      ],
    },
  ],
};

export default sidebars;
