import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  blogSidebar: [
    {
      type: 'category',
      label: 'علوم الحاسب الآلي',  // التخصص الأساسي
      items: [
        {
          type: 'link',
          label: 'تجربة عبدالمجيد بكر - خريج علوم الحاسب الآلي',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/abdulmajeed-bakr',
        },
        {
          type: 'link',
          label: 'تجربة حميدة خان - خريجة علوم الحاسب الآلي',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/hamida-khan',
        },
        {
          type: 'link',
          label: 'تجربة رهف مراد - خريجة علوم الحاسب الآلي',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/rahaf-murad',
        },
      ],
    },
    {
      type: 'category',
      label: 'هندسة البرمجيات',  // التخصص الثاني
      items: [
        {
          type: 'link',
          label: 'تجربة لينا نجدي - هندسة البرمجيات',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/Lina',
        },
        {
          type: 'link',
          label: 'تجربة شادي رزق - هندسة البرمجيات',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/Shadi',
        },
        {
          type: 'link',
          label: 'تجربة الكاتو - هندسة البرمجيات',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/elcato',
        },
      ],
    },
  ],
};

export default sidebars;
