import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  blogSidebar: [
    {
      type: 'category',
      label: 'علوم الحاسب الآلي',  
      items: [
        {
          type: 'link',
          label: 'تجربة عبدالمجيد بكر',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/abdulmajeed-bakr', // تجربة عبدالمجيد
        },
        {
          type: 'link',
          label: 'تجربة حميدة خان',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/hamida-khan', // تجربة حميدة
        },
        {
          type: 'link',
          label: 'تجربة رهف مراد',
          href: 'https://uqucc-majors.sb.sa/blog/cs-exp/rahaf-murad', // تجربة رهف
        },
      ],
    },
    {
      type: 'category',
      label: 'هندسة البرمجيات',  
      items: [
        {
          type: 'link',
          label: 'تجربة لينا نجدي',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/Lina', // تجربة لينا
        },
        {
          type: 'link',
          label: 'تجربة شادي رزق',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/Shadi', // تجربة شادي
        },
        {
          type: 'link',
          label: 'تجربة الكاتو',
          href: 'https://uqucc-majors.sb.sa/blog/se-exp/elcato', // تجربة الكاتو
        },
      ],
    },
  ],
};

export default sidebars;
